/**
 * StadiumOS AI — Agent Recommendations Routing Handlers.
 * 
 * Exposes API routes for reviewing and approving recommendations generated by the AI agent mesh.
 */

import { Router, Response, NextFunction } from "express";
import { PrismaIncidentRepository } from "../../../infrastructure/repositories/incidentRepository";
import { PrismaGateRepository } from "../../../infrastructure/repositories/gateRepository";
import { GateService } from "../../../application/services/gateService";
import { CacheService } from "../../../infrastructure/cache/cacheService";
import { authenticateMiddleware, requireRole } from "../../../infrastructure/security/rbac";
import { UserRole, GateStatus } from "../../../domain/enums";
import { EntityNotFoundError, BusinessRuleViolationError } from "../../../domain/exceptions";
import { logger } from "../../../infrastructure/logging/logger";

const router = Router();
const incidentRepo = new PrismaIncidentRepository();
const gateRepo = new PrismaGateRepository();
const cacheService = new CacheService();
const gateService = new GateService(gateRepo, cacheService);

// 1. Fetch all pending recommendations
router.get(
  "/recommendations",
  authenticateMiddleware,
  requireRole(UserRole.OPERATOR),
  async (req: any, res: Response, next: NextFunction) => {
    try {
      const activeIncidents = await incidentRepo.listActive();
      const list: any[] = [];

      for (const incident of activeIncidents) {
        if (incident.ai_recommendation) {
          try {
            const parsed = JSON.parse(incident.ai_recommendation);
            if (Array.isArray(parsed)) {
              parsed.forEach((rec) => {
                list.push({
                  ...rec,
                  incident_id: incident.id,
                  severity: incident.severity
                });
              });
            }
          } catch (jsonErr) {
            logger.warn(`Failed to parse AI recommendations for incident ${incident.id}: ${incident.ai_recommendation}`);
          }
        }
      }

      res.status(200).json(list);
    } catch (err) {
      next(err);
    }
  }
);

// 2. Approve and execute recommendation (Operator validation)
router.post(
  "/recommendations/:id/approve",
  authenticateMiddleware,
  requireRole(UserRole.OPERATOR),
  async (req: any, res: Response, next: NextFunction) => {
    const { action_type, target_entity_id } = req.body;

    if (!action_type || !target_entity_id) {
      return res.status(400).json({
        success: false,
        error: "Missing required approval params: action_type, target_entity_id."
      });
    }

    try {
      logger.info({ recId: req.params.id, action_type }, "Approving agent recommendation");

      // Execute recommendation action type
      if (action_type === "OPEN_GATE" || action_type === "CLOSE_GATE") {
        const targetStatus = action_type === "OPEN_GATE" ? GateStatus.OPEN : GateStatus.CLOSED;
        
        await gateService.updateGateStatus(target_entity_id, {
          status: targetStatus,
          reason: `Approved AI recommendation ${req.params.id}`
        });

        res.status(200).json({
          success: true,
          message: `Recommendation approved. Target gate status updated to ${targetStatus}.`
        });
      } else {
        throw new BusinessRuleViolationError(
          "Unsupported recommendation execution action type",
          `Action type '${action_type}' is not supported.`
        );
      }
    } catch (err) {
      next(err);
    }
  }
);

export { router as agentRouter };
export default agentRouter;
