"""
StadiumOS AI — Domain Enumerations.

Enumerations define the finite set of valid values for categorical fields
across the domain. Using Python enums (backed by str) provides:
    1. Type safety — IDE and mypy catch invalid assignments at edit time.
    2. Serialization — str-based enums serialize directly to JSON strings
       in Pydantic models without custom encoders.
    3. Database compatibility — SQLAlchemy stores the string value, making
       database rows human-readable in raw SQL queries.

Design Decision:
    All enums inherit from (str, Enum) rather than using StrEnum (Python 3.11+)
    to maintain compatibility with SQLAlchemy's Enum type adapter, which
    expects string values for column storage.
"""

from enum import Enum


class UserRole(str, Enum):
    """
    Authorization roles for Role-Based Access Control (RBAC).

    The role hierarchy is:
        ADMIN > OPERATOR > VOLUNTEER > FAN

    Each role grants a superset of the permissions of the roles below it.
    """

    ADMIN = "admin"
    """Full system access: configuration, overrides, user management."""

    OPERATOR = "operator"
    """Command center staff: approve recommendations, manage incidents."""

    VOLUNTEER = "volunteer"
    """Field staff: report and resolve incidents in assigned sectors."""

    FAN = "fan"
    """Public spectators: read-only access to navigation and transit info."""


class IncidentSeverity(str, Enum):
    """
    Severity classification for stadium incidents.

    Severity levels determine automatic escalation paths:
        - LOW/MEDIUM: Handled by the assigned volunteer.
        - HIGH: Escalated to the sector operator.
        - CRITICAL: Triggers emergency protocols and direct 911 dispatch.
    """

    LOW = "low"
    """Minor issue: lost item, minor facility complaint."""

    MEDIUM = "medium"
    """Moderate issue: small crowd buildup, minor injury requiring first aid."""

    HIGH = "high"
    """Serious issue: large crowd bottleneck, medical emergency."""

    CRITICAL = "critical"
    """Life-threatening or mass-safety event: structural failure, stampede risk."""


class IncidentStatus(str, Enum):
    """
    Lifecycle status of a stadium incident.

    State transitions follow a strict linear flow:
        REPORTED → ACKNOWLEDGED → IN_PROGRESS → RESOLVED
                                              → ESCALATED (branch)
    """

    REPORTED = "reported"
    """Initial state: incident has been submitted but not yet reviewed."""

    ACKNOWLEDGED = "acknowledged"
    """An operator or volunteer has seen the incident and accepted responsibility."""

    IN_PROGRESS = "in_progress"
    """Active response: a volunteer is physically addressing the incident."""

    RESOLVED = "resolved"
    """Terminal state: the incident has been successfully handled."""

    ESCALATED = "escalated"
    """The incident exceeded the current handler's capability and was escalated."""


class GateStatus(str, Enum):
    """
    Operational status of a stadium entry/exit gate.

    Gate status is updated by both IoT sensors (automatic) and operators
    (manual override). The Digital Twin State Manager consumes these values
    to compute crowd flow models.
    """

    OPEN = "open"
    """Gate is operational and accepting spectator flow."""

    CLOSED = "closed"
    """Gate is shut down — no entry or exit permitted."""

    RESTRICTED = "restricted"
    """Gate is open but operating at reduced capacity (e.g., VIP only, exit only)."""

    CONGESTED = "congested"
    """Gate is open but experiencing high-density crowding (auto-detected by sensors)."""

    MAINTENANCE = "maintenance"
    """Gate is offline for maintenance or equipment repair."""


class VolunteerStatus(str, Enum):
    """
    Availability status of a stadium volunteer.

    Volunteers update their status via the mobile app. The Security & Medical
    Agent uses this status to filter available volunteers when dispatching
    responses to incidents.
    """

    AVAILABLE = "available"
    """Volunteer is on-shift and ready to accept task assignments."""

    ASSIGNED = "assigned"
    """Volunteer is currently assigned to an active incident."""

    ON_BREAK = "on_break"
    """Volunteer is on a scheduled break and should not receive new assignments."""

    OFF_DUTY = "off_duty"
    """Volunteer's shift has ended. Excluded from dispatch queries."""


class RecommendationStatus(str, Enum):
    """
    Lifecycle status of an AI agent recommendation.

    Every recommendation generated by the agentic mesh must pass through
    human-in-the-loop approval before execution. This prevents autonomous
    AI actions from causing unsafe crowd movements.
    """

    PENDING = "pending"
    """Recommendation is awaiting operator review on the Command Center."""

    APPROVED = "approved"
    """Operator has approved the recommendation for execution."""

    REJECTED = "rejected"
    """Operator has rejected the recommendation with documented reasoning."""

    EXECUTED = "executed"
    """The approved recommendation has been dispatched to downstream systems."""

    EXPIRED = "expired"
    """The recommendation was not acted upon within its validity window."""
